// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7Aj479ntUZjde11EU8kG8GEAR2yr14U',
    appId: '1:904684480635:web:c5f0e5a6da527741785ade',
    messagingSenderId: '904684480635',
    projectId: 'sportrent-198c8',
    authDomain: 'sportrent-198c8.firebaseapp.com',
    storageBucket: 'sportrent-198c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUcIb1tmvhVILBWXVKm1mqL-4ooUHbSk',
    appId: '1:904684480635:android:fd3003762e434184785ade',
    messagingSenderId: '904684480635',
    projectId: 'sportrent-198c8',
    storageBucket: 'sportrent-198c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBlRvykwVEZj2T-iya0jTo9Si4HvB650',
    appId: '1:904684480635:ios:49a3165fbe539aee785ade',
    messagingSenderId: '904684480635',
    projectId: 'sportrent-198c8',
    storageBucket: 'sportrent-198c8.firebasestorage.app',
    iosBundleId: 'com.example.sportRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgBlRvykwVEZj2T-iya0jTo9Si4HvB650',
    appId: '1:904684480635:ios:49a3165fbe539aee785ade',
    messagingSenderId: '904684480635',
    projectId: 'sportrent-198c8',
    storageBucket: 'sportrent-198c8.firebasestorage.app',
    iosBundleId: 'com.example.sportRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf7Aj479ntUZjde11EU8kG8GEAR2yr14U',
    appId: '1:904684480635:web:b52845d856678132785ade',
    messagingSenderId: '904684480635',
    projectId: 'sportrent-198c8',
    authDomain: 'sportrent-198c8.firebaseapp.com',
    storageBucket: 'sportrent-198c8.firebasestorage.app',
  );
}
